# Site settings
title: "Eric A Mann"
description: "Personal profile and porfolio for Eric A Mann"
url: https://eamann.com
enforce_ssl: eamann.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Eric A Mann"
resume_title:                   "Tekton"
resume_contact_email:           "eric@eamann.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ericmann/ericmann.github.io"
  resume_twitter_url:           "https://twitter.com/ericmann"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ericallenmann"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://ttmm.io"

# Design settings
resume_theme:                   default

collections:
  speaking:
    output: false
  roles:
    output: false

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
